#!/bin/bash
##to update the server ##
sudo apt-get update
sudo apt-get install apache2 -y
sudo echo"<h1> Woorldshould be ready to face the most danguress desiese called corona<h1>" > /var/www/html/index.html/
sudo service apache2 restart
